"""followers

Revision ID: 1067d8c241c3
Revises: ea2e6aa90c78
Create Date: 2021-12-17 19:39:58.718261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1067d8c241c3'
down_revision = 'ea2e6aa90c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['flasklogin-users.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['flasklogin-users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
