"""empty message

Revision ID: 33943bc3fb9f
Revises: 8393e34535a8
Create Date: 2021-12-16 23:25:21.779757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33943bc3fb9f'
down_revision = '8393e34535a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_public', sa.Boolean(), nullable=True))
    op.add_column('blogs', sa.Column('blog_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_private')
    op.drop_column('blogs', 'blog_public')
    # ### end Alembic commands ###
