"""Added items and cars

Revision ID: 93b807a9a55e
Revises: 1067d8c241c3
Create Date: 2021-12-18 07:50:36.723989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b807a9a55e'
down_revision = '1067d8c241c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bought_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=40), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('bought_at', sa.Date(), nullable=True),
    sa.Column('warrenty_expire', sa.Date(), nullable=True),
    sa.Column('item_price', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['flasklogin-users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('bought_at', sa.Date(), nullable=False),
    sa.Column('service_period', sa.Integer(), nullable=True),
    sa.Column('next_service', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['flasklogin-users.user_id'], ),
    sa.PrimaryKeyConstraint('car_id'),
    sa.UniqueConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('bought_items')
    # ### end Alembic commands ###
