"""Initial migration

Revision ID: c4c99e1ea225
Revises: 
Create Date: 2021-12-14 23:09:12.995562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c99e1ea225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=80), nullable=False),
    sa.Column('blog_content', sa.Text(), nullable=True),
    sa.Column('blog_created', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('flasklogin-users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flasklogin-users')
    op.drop_table('blogs')
    # ### end Alembic commands ###
