"""changed blog_publicity

Revision ID: ea2e6aa90c78
Revises: 33943bc3fb9f
Create Date: 2021-12-16 23:34:09.899525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2e6aa90c78'
down_revision = '33943bc3fb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_publicity', sa.Integer(), nullable=True))
    op.drop_column('blogs', 'blog_public')
    op.drop_column('blogs', 'blog_private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('blog_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_publicity')
    # ### end Alembic commands ###
